name: Test running script for production

on:
  push:
    branches: [  "feature-merge-hepmc3-and-singles-submission" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    # Note: this workflow must run on linux 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        run: |
          eic-info

          # Test running hepmc3 file
          DETECTOR_CONFIG="epic_craterlake" \
          DETECTOR_VERSION="main" \
          COPYRECO=FALSE \
          COPYLOG=FALSE \         
          /opt/campaigns/hepmc3/run.sh /work/eic2/EPIC/EVGEN/DIS/NC/18x275/minQ2=1/pythia8NCDIS_18x275_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1 hepmc3.tree.root 10

          # Test running singles file
          DETECTOR_CONFIG="epic_craterlake" \
          DETECTOR_VERSION="main" \
          COPYRECO=FALSE \
          COPYLOG=FALSE \         
          /opt/campaigns/hepmc3/run.sh /work/eic2/EPIC/EVGEN/SINGLE/e+/100MeV/130to177deg/e+_100MeV_130to177deg	steer 10
